### ISSUE TITLE
[issue] Can't get Wacom tablet to work with Spine

### ISSUE THREAD

**Issue by bencresty** [EsotericSoftware/spine-editor#677]
Using a Wacom tablet pen in default mode (of Wacom) when in Mesh Edit - Create mode in Spine, I had Spine switching randomly to 'Delete' mode when trying to drag vertices or click'n'drag to add a vertex and slide to create an (inner) edge. I followed the Spine faq to use Spine with a tablet and have `Double click shortcuts` turned off in settings (and restarted Spine after).

I checked the Wacom settings; There were no actions a user can set for this pen tip.
![image](https://user-images.githubusercontent.com/69322733/181483436-bb58c8d2-84cc-44a4-bdd4-154f777588e1.png)

But then I saw that I can configure the double click speed of the pen tip and set it to `off` in the Wacom settings for the Spine program. So I did and it seems like this helped getting rid of the issue.

These are the settings I'm using now:
![image](https://user-images.githubusercontent.com/69322733/181485929-dd7a8192-2b59-486a-88ff-aaed99259fbe.png)

So it seems like it was first firing double click actions for some reason and looks like Spine has something connected to it causing edit mesh to go into Delete mode when it happens. Which I don't quite understand, because I'm not double clicking in any way, I'm putting the pen on the tablet, holding it for a little and then start dragging with the pen (all without the pen leaving the tablet). But by the result of turning the pen tip double click feature off it seems to work so far and I did some real testing for a few minutes after.

If this is the case Spine is probably either not turning off double click actions in mesh edit mode, or something else is not working fine with default Wacom pen settings.

This was what I recorded before turning off the double click on the pen tip: note that I'm only using the pen tip. So no keyboard keys or tablet buttons and no pen buttons.

https://user-images.githubusercontent.com/69322733/181483052-9eae7d2e-3fdb-4060-8463-09797edbf1fc.mp4

**Comment by bencresty** [comment]
Alright, tried real hard to work with a pen in Spine, but it's basically impossible. First I found out that again Spine was just 'randomly' toggling from Pose mode to Weight mode without any reason to and without pressing any key or tablet button. Like it's reaction to some kind of gesture.

Than, when going into Mesh edit mode again again it didn't work with the pen. It's not only switching to Create Mode  AND directly after to Delete Mode when in Modify mode, also there is a pretty extreme offset between the location of the pen and the position a vertex is on the screen. Besides this it doesn't catch a vertex directly, but only while already dragging pretty far away.

I'm sorry, don't want to be harsch, but I really don't have any clue if and how other people are actually working with a Wacom pen in Spine (would be happy to know if they figured a way or if I'm completely missing something here), but by this experience and after setting everything according to the faq AND made an adjustment to the wacom settings to turn off double click, to me this makes working in Spine with a Wacom tablet just impossible because of these issues. 

If these are fixed tho for me this would be a way better workflow then mouse as I can already feel it speeds up everything a lot as the coordination with the screen is much better compared to using a mouse.

To illustrate this, please see below video. There's only one time I'm using a button on the Wacom tablet and that's to simulate a J-key to pan the screen with the pen. All other actions are just pressing and moving the tip on the tablet.

Uploading Tablet-Unusable.mp4…

**Comment by bencresty** [comment]
Alright, it now seems to work a lot better, if not completely. But not with the advice of the faq, but with these states:

- Turning ON the double click shortcuts in Spine (so not OFF like the faq says)
- Turning OFF Windows Ink in the Wacom tablet settings
(- Perhaps the fact that I set the pen tip to disable double clicks might have helped too, not sure about that tho, as I never even double clicked, not even on purpose.)

It seems like Windows Ink is doing all kinds of crazy actions and/or looks for gestures we don't want?

When having 'Double Click shortcuts' turned OFF in Spine, as the faq advises to do with tablets, suddenly when using Ctrl + pen to select an image to connect a bone to in Create mode suddenly other images, which aren't even close to overlapping the cursor, get selected too. So this makes it impossible to work in the Create mode. I didn't go further in testing that as I obviously use create mode all the time and this ctrl-select method all the time.

After working for about half an hour with these new settings as described here I didn't see any problem so far. I used Mesh edit, Weights, drawing bones, create mode etc. So it looks like this made the tablet function as expected. Very happy about that!

But it seems there's still something not quite right with the 'Double Click Shortcuts' setting when turned off as it's clearly causing issues here.

**Comment by NathanSweet** [comment]
Some of my colleagues use a pen daily (I'll direct them to give their input here), but it's been years for me. I remember needing to use this "Fix My Pen" tool to make my Wacom CTH-480S-S Intuos usable on Windows:
https://viziblr.com/news/2011/8/13/fix-my-pen-makes-your-wacom-tablet-just-work-on-windows-7.html
I don't know if that's still needed these days, but I wouldn't be surprised.

I see that edit mesh mode doesn't respect disabling double click shortcuts, it still deletes on double click. We'll fix that and do an audit for other double click handling.

Switching between tools randomly sounds like the behavior you get when right clicking, which toggles to the previously used tool (both in edit mesh mode and outside it). Most pens have a button that gives you right click when you tap with the button held. It might be that your finger is hitting that button, or the Wacom driver or some Windows Ink or other settings are screwy. Something must be causing Spine to see a right click.

We could add a setting to disable right click tool changing. We have planned a setting to choose the two tools explicitly instead of using the previous tool, so you always know what you'll get when you right click. That setting could have "off".

Thanks for the video. I see the "tap distance" you need to drag for the vertex to start moving is very large! That's super weird. I haven't been able to reproduce that. I tried many settings combinations (double click on/off, bone scale, etc). A mouse vs pen and pen settings shouldn't matter, as the distance is based on how many pixels the mouse moves. Maybe you can post or email (contact@esotericsoftware.com) the star project and image?

> When having 'Double Click shortcuts' turned OFF in Spine, as the faq advises to do with tablets, suddenly when using Ctrl + pen to select an image to connect a bone to in Create mode suddenly other images, which aren't even close to overlapping the cursor, get selected too.

Holding `ctrl` with the bone `Create` tool lets you select attachments by clicking them and lets you box select by dragging. It looks like there is a bug where the drag does not use a "tap distance", it starts the drag and box select if you move the mouse even 1 pixel. We'll get this fixed! It's very easy with a pen to move the mouse slightly when clicking. The box select will select all attachment intersecting the box, while clicking will only select the hovered attachment.

**Comment by NathanSweet** [comment]
Oh, I see apparently the Fix My Pen tool is no longer needed, if you follow these instructions:
https://viziblr.com/news/2013/6/23/the-windows-and-wacom-tablet-nightmare-is-over.html

**Comment by NathanSweet** [comment]
A couple links, this page seems pretty thorough:
http://www.designimage.co.uk/how-to-remove-the-annoying-wacom-circles-in-windows/
There's quite a few things in the way of sane pen usage on Windows!

This page can be helpful to ensure there aren't any problems with your pen:
http://101.wacom.com/userhelp/en/TestingPen.htm
A hardware problem is not unheard of and could cause you to lose some hair.

**Comment by bencresty** [comment]
@NathanSweet Thanks a lot for your detailed replies. Looks like I did already do everything according to the link to 'avoid wacom nightmare' you provided, which was basically switching off 'Windows Ink'. That indeed fixed all issues that appearently came from Windows Ink.

I understand you sending the link to test the tablet hardware, but I'm using this tablet everyday all day in graphical applications without any issues. Please note: they didn't appeared to have issues because I had switched off Windows Ink for those once!! So probably they had the same issues when it was still turned on.
For Spine tho, I needed to add a different configuration, so had to add the Spine application to the wacom settings to have own settings. But apparently by default Wacom turns WIndows Ink ON on newly added applications, which was causing most of the issues... And I just forgot about that nasty Windows Ink and to check that, sorry for that.

> I see that edit mesh mode doesn't respect disabling double click shortcuts, it still deletes on double click. We'll fix that and do an audit for other double click handling.

Ah, that explains why. Good catch!
 
> Switching between tools randomly sounds like the behavior you get when right clicking, which toggles to the previously used tool (both in edit mesh mode and outside it). Most pens have a button that gives you right click when you tap with the button held. It might be that your finger is hitting that button, or the Wacom driver or some Windows Ink or other settings are screwy. Something must be causing Spine to see a right click.

This was Windows Ink doing it. After turning it off I didn't see this happening anymore. Neither I saw the offset cursor anymore.

> We could add a setting to disable right click tool changing. We have planned a setting to choose the two tools explicitly instead of using the previous tool, so you always know what you'll get when you right click. That setting could have "off".

Don't think it's needed anymore, but could come in handy if not too much trouble to add.

> Thanks for the video. I see the "tap distance" you need to drag for the vertex to start moving is very large! That's super weird. I haven't been able to reproduce that. I tried many settings combinations (double click on/off, bone scale, etc). A mouse vs pen and pen settings shouldn't matter, as the distance is based on how many pixels the mouse moves. Maybe you can post or email ([contact@esotericsoftware.com](mailto:contact@esotericsoftware.com)) the star project and image?

I'm pretty sure that was Windows Ink doing that. My guess is it was waiting to read some type of gesture first before doing something and doesn't catch up after. Not going to break my head on what 'Windows Ink' does tho. I don't know any software that is happy with that windows feature and to my knowledge it's only causing problems and confusion. At least in graphical software. In retrospect I know that Affinity products had or has the same problems with Windows Ink.

The star project was already removed, but looks like you don't need it anymore as I'm pretty sure that didn't turn out to be an issue in Spine, but in Windows Ink.

> Holding `ctrl` with the bone `Create` tool lets you select attachments by clicking them and lets you box select by dragging. It looks like there is a bug where the drag does not use a "tap distance", it starts the drag and box select if you move the mouse even 1 pixel. We'll get this fixed! It's very easy with a pen to move the mouse slightly when clicking. The box select will select all attachment intersecting the box, while clicking will only select the hovered attachment.

Ah, this is great to read, because this is still an issue. I thought it was over when turning ON double click features and it looked like it did, but I still had this issue later whith this setting enabled. So it didn't seem to matter what this setting was set to.
For the record: the other image, that shouldn't be selected, was by far not within a 1px distance. More like 100 pixels or more. But I think that's why you bring up an issue with 'tap distance', right?
Releaving to read this is found and will be fixed!

FYI For the rest I had a very great workflow experience yesterday while rigging using a pen. Had a pretty great speed boost. The only things that are still difficult for me to use well are the zoom animation which is also hard to use when working zoomed in because the animation keeps going too far in or out (https://github.com/EsotericSoftware/spine-editor/issues/676). And the fact that I'm used to use spacebar for dragging (like Adobe producst and Affinity), and can't use spacebar because it's already set to start/stop. But fixed that by adding `J` to a Wacom key, which was difficult to not accidentally hit space bar, but that's my problem. I'll get used to that! :)

I think with the two fixes you announced things should work fine with Wacom tablets. As far as I can tell after working with it for a day in SETUP mode (didn't use it in ANIMATE mode yet). And with the extra setting to be able to turn off right click behaviour we can be absolutely sure that cannot ever happen again!

If you could add a setting to turn off the zoom animations that would make it really ideal!! That would be really awesome and solve an important use issue here!

**Comment by NathanSweet** [comment]
We've improved the FAQ a bit:
http://esotericsoftware.com/support#Which-settings-improve-use-of-a-pen-tablet-or-touchpad%2Ftrackpad%3F

In 4.1.07 we've fixed the double setting not being respected in some cases and fixed the `Create` tool click / box selection drag distance.

Glad to hear it's working well for you now! We'll take a look at the zoom issue you've opened. Cheers!

**Comment by bencresty** [comment]
@NathanSweet  perhaps I'm missing something, please correct me if I am. But when using the Wacom pen I still see multi selections happening when using the 'create' tool/mode to bind a bone to an image, which isn't happening when using mouse. I elieve you were going to fix that or already fixed it in a later version? Just to make sure that is still an issue in the version I'm using here now (4.1.06) with Wacom

**Comment by NathanSweet** [comment]
The `Create` tool selections should be fixed in 4.1.07. Likely we'll release that tonight!

Feel free to post to an existing issue if you have problems, even if the issue has been closed. We see all comments to any issue and we can reopen an issue if needed.

**Comment by bencresty** [comment]
Great news! Thanks for the quick action!
